server:
  # 运行端口号
  port: 8101
spring:
  application:
    # 服务名称
    name: eureka-client
eureka:
  client:
    # 注册到Eureka的注册中心
    register-with-eureka: true
    # 获取注册实例列表
    fetch-registry: true
    # 配置注册中心地址
    service-url:
      defaultZone: http://replica1:8002/eureka/,http://replica2:8003/eureka/ #同时注册到两个注册中心